---
detectors:
  DuplicateMethodCall:
    exclude:
    - OpenApi::RSpec::SchemaParser#deep_body_keys
    - OpenApi::RSpec::SchemaParser#get_deep_keys
    - OpenApi::RSpec::SchemaParser#initialize
    - OpenApi::RSpec::SchemaParser#openapi_body_params
    - OpenApi::RSpec::SchemaParser#schema_for_url_and_request_method_and_response_status
    - OpenApi::RSpec::SchemaParser#openapi_form_data_params
  FeatureEnvy:
    exclude:
    - OpenApi::RSpec::SchemaParser#deep_body_keys
    - OpenApi::RSpec::SchemaParser#get_deep_keys
    - OpenApi::RSpec::SchemaParser#openapi_required_form_data_params
    - OpenApi::RSpec::SchemaParser#openapi_required_path_params
    - OpenApi::RSpec::SchemaParser#openapi_required_query_string_params
    - OpenApi::RSpec::SchemaParser#openapi_form_data_params
  NestedIterators:
    exclude:
    - OpenApi::RSpec::SchemaParser#deep_body_keys
    - OpenApi::RSpec::SchemaParser#get_deep_keys
    - OpenApi::RSpec::SchemaParser#initialize
    - OpenApi::RSpec::SchemaParser#openapi_body_params
    - OpenApi::RSpec::SchemaParser#openapi_form_data_params
  TooManyInstanceVariables:
    exclude:
    - OpenApi::RSpec::SchemaParser
  TooManyMethods:
    exclude:
    - OpenApi::RSpec::SchemaParser
  TooManyStatements:
    exclude:
    - initialize
    - OpenApi::RSpec::SchemaParser#deep_body_keys
    - OpenApi::RSpec::SchemaParser#get_deep_keys
    - OpenApi::RSpec::SchemaParser#openapi_body_params
    - OpenApi::RSpec::SchemaParser#openapi_form_data_params
  UncommunicativeVariableName:
    exclude:
    - OpenApi::RSpec::SchemaParser#get_deep_keys
    - OpenApi::RSpec::SchemaParser#initialize
    - OpenApi::RSpec::SchemaParser#openapi_body_params
    - OpenApi::RSpec::SchemaParser#openapi_form_data_params
    - OpenApi::RSpec::SchemaParser#openapi_path_params
    - OpenApi::RSpec::SchemaParser#openapi_query_string_params
    - OpenApi::RSpec::SchemaParser#openapi_required_form_data_params
    - OpenApi::RSpec::SchemaParser#openapi_required_path_params
    - OpenApi::RSpec::SchemaParser#openapi_required_query_string_params
    - OpenApi::RSpec::SchemaParser#request_path_params
    - OpenApi::RSpec::SchemaParser#schema_for_url_and_request_method_body_parameters
    - OpenApi::RSpec::SchemaParser#schema_for_url_and_request_method_form_data_parameters
    - OpenApi::RSpec::SchemaParser#schema_for_url_and_request_method_path_parameters
    - OpenApi::RSpec::SchemaParser#schema_for_url_and_request_method_query_string_parameters
  UtilityFunction:
    exclude:
    - OpenApi::RSpec::SchemaParser#has_documented_param_in_openapi_url_fragments
    - OpenApi::RSpec::SchemaParser#openapi_url_fragment_name

  IrresponsibleModule:
    enabled: false

exclude_paths:
  - vendor/bundle
